//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Word
{
    using System;
    using System.Collections.Generic;
    
    public partial class pay
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date_paymant { get; set; }
        public Nullable<int> category_id { get; set; }
        public Nullable<int> user_id { get; set; }
        public string name { get; set; }
        public Nullable<int> count { get; set; }
        public Nullable<double> price { get; set; }
        public Nullable<double> cost { get; set; }
    
        public virtual Categoty Categoty { get; set; }
        public virtual users users { get; set; }
    }
}
